Repository nile27/Slid-to-do-Refactoring, pull requests merged in 2025-08, with the labels that each got.

#3 [Design, Feature] 목표 리스트 디자인 및 로딩스피너 추가
  package-lock.json
  package.json
  public/sidebar/note.svg
  src/app/goals/page.tsx
  src/app/notes/page.tsx
  src/app/todos/page.tsx
  src/components/common/hasmore-loading.tsx
  src/components/common/modal/side-modal.tsx
  src/components/goals/goal-header.tsx
  src/components/goals/prograss.tsx
  src/components/goals/todo-list.tsx
  src/components/navigation/components/client-sidebar.tsx
  src/components/navigation/components/goal-modal.tsx
  src/components/notes/edit.tsx
  src/components/notes/list.tsx
  src/components/notes/select.tsx
  src/components/notes/write.tsx
  src/lib/goals/api.ts
  src/lib/notes/api.ts
  src/types/goals.ts
  src/types/todos.ts
Labels: Feature, Design

#5 [Feature] useTimer
  src/app/dashboard/components/body/goal-title-header.tsx
  src/app/dashboard/components/body/goal-todo-container.tsx
  src/app/dashboard/components/body/todo-progress.tsx
  src/app/dashboard/components/header/focus-timer.tsx
  src/app/dashboard/components/header/header-container.tsx
  src/app/dashboard/page.tsx
  src/components/goals-parts/goal-todo-container.tsx
  src/hooks/use-timer.ts
  src/store/store.ts
Labels: Feature

#6 [Refactor, Feature] 회원가입 vaildation 및 파일 업로드 드래그앤드롭
  package-lock.json
  package.json
  src/app/goals/page.tsx
  src/app/signup/page.tsx
  src/components/common/input-form.tsx
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/edit-todo-modal.tsx
  src/components/goals-parts/goal-title-header.tsx
  src/components/goals-parts/goal-todo-container.tsx
  src/components/goals-parts/todo-progress.tsx
  src/components/goals/prograss-motion.tsx
Labels: Feature, Refactor

#7 [Rename] 일반 함수 => 화살표 함수 변경
  public/dashboard/clock-filled.svg
  public/dashboard/pause.svg
  public/dashboard/play.svg
  public/dashboard/reset.svg
  public/dashboard/stop.svg
  public/dashboard/timer-done.svg
  src/app/dashboard/components/header/focus-timer.tsx
  src/app/dashboard/components/header/header-container.tsx
  src/app/dashboard/components/header/timer-done-modal.tsx
  src/app/dashboard/util/util.ts
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/not-found.tsx
  src/app/providers/timer-provider.tsx
  src/components/common/loading-spinner.tsx
  src/components/common/todo-item.tsx
  src/components/goals-parts/todo-progress.tsx
  src/components/goals/goal-header.tsx
  src/components/goals/prograss-motion.tsx
  src/components/goals/prograss.tsx
  src/components/goals/todo-list.tsx
  src/components/navigation/components/client-sidebar.tsx
  src/components/navigation/components/side-timer.tsx
  src/components/style/hamburger-toggle.tsx
  src/components/style/utils.ts
  src/hooks/use-infinite-scroll.ts
  src/hooks/use-timer.ts
  src/lib/common-api.ts
  src/store/store.ts
  src/store/timer-store.ts
Labels: Rename

#8 [Design]skeleton UI 변경
  components.json
  package-lock.json
  package.json
  src/app/dashboard/components/header/new-addtodo.tsx
  src/app/globals.css
  src/components/goals-parts/goal-todo-container.tsx
  src/components/notes/edit.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/skeleton/dashboard/new-addtodo-skeleton.tsx
  src/components/ui/skeleton/goals/goal-title-header-skeleton.tsx
  src/components/ui/skeleton/goals/goals-todo-container-skeleton.tsx
  src/lib/utils.ts
Labels: Design

#11 [Refactor] api 통신 통합
  src/app/dashboard/components/header/header-container.tsx
  src/app/goals/[goalId]/page.tsx
  src/app/notes/write/page.tsx
  src/components/goals-parts/goal-title-header.tsx
  src/components/goals-parts/goal-todo-container.tsx
  src/components/goals-parts/todo-progress.tsx
  src/components/goals/goal-header.tsx
  src/components/goals/prograss-motion.tsx
  src/components/goals/prograss.tsx
  src/components/navigation/components/goal-modal.tsx
  src/components/navigation/components/sidebar-profile.tsx
  src/components/notes/edit.tsx
  src/components/notes/write.tsx
  src/lib/common-api.ts
  src/lib/goals/api.ts
  src/lib/notes/api.ts
  src/lib/query-keys.ts
  src/lib/todos/api.ts
  src/lib/users/api.ts
  src/types/goals.ts
  src/types/notes.ts
  src/types/todos.ts
Labels: Refactor
